### ISSUE TITLE
Continuos Integration Tool

### ISSUE THREAD

**Issue by guilhermeddf** [schdief/moveez#94]
Does this project use any Continuous Integration Tool? If so, is it online? (TravisCI, CircleCI), or offline tool (Jenkins, Hudson).

**Comment by schdief** [comment]
@guilhermeddf we started with Jenkins and switched to Azure DevOps Pipelines - you can visit it here:
https://dev.azure.com/Schdieflaw0018/moveez/_build/latest?definitionId=2&branchName=master

**Comment by guilhermeddf** [comment]
@schdief Thank you!
